Repository microsoft/finops-toolkit, pull requests merged in 2023-03, with the labels that each got.

#69 Add containers and settings.json to hub
  src/modules/Microsoft.Resources/deploymentScripts/deploy.bicep
  src/modules/Microsoft.Resources/deploymentScripts/readme.md
  src/modules/hub.bicep
  src/modules/scripts/Copy-FileToAzureBlob.ps1
  src/templates/finops-hub/main.bicep
Labels: Area: ARM, Needs: Review 👀

#77 Move data dictionary
  docs/README.md
  docs/data-dictionary.md
  docs/reports/README.md
  docs/reports/terms.md
  docs/terms.md
Labels: Area: Documentation, Needs: Review 👀

#79 Update feature branch creation guidance
  src/README.md
Labels: Area: Documentation, Micro PR 🔬, Area: GitHub, Needs: Review 👀

#87 Add bicep registry docs and scripts
  .vscode/settings.json
  src/architecture.md
  src/bicep-registry/README.md
  src/scripts/Build-Bicep.ps1
  src/scripts/Build-Toolkit.ps1
  src/scripts/Deploy-Toolkit.ps1
  src/scripts/New-Directory.ps1
  src/templates/finops-hub/test/main.test.bicep
Labels: Area: Documentation, Area: ARM, Needs: Review 👀

#80 Update getting started guidance
  docs/README.md
  docs/data-processing.md
  docs/reports/README.md
Labels: Area: Documentation, Micro PR 🔬, Needs: Review 👀

#85 Data retention settings
  docs/templates/finops-hub.md
  docs/templates/modules/hub.md
  src/modules/hub.bicep
  src/modules/scripts/Copy-FileToAzureBlob.ps1
  src/templates/finops-hub/main.bicep
Labels: Area: Data factory, Area: ARM, Needs: Review 👀

#91 Add ADF dataset for ms-cm-exports folder
  src/modules/datasets/ms_cm_exports.bicep
Labels: Type: Feature 💎, Status: 🔬 Code review, Area: Data factory, Area: ARM, Needs: Review 👀

#97 A module to store the primary key of a storage account in a KeyVault secret.
  src/modules/secrets/storageaccountsecret.bicep
Labels: Area: Data factory, Area: ARM

#88 Add scheduled-action bicep module
  src/bicep-registry/scheduled-action/README.md
  src/bicep-registry/scheduled-action/main.bicep
  src/bicep-registry/scheduled-action/main.json
  src/bicep-registry/scheduled-action/metadata.json
  src/bicep-registry/scheduled-action/test/main.test.bicep
  src/bicep-registry/scheduled-action/version.json
  src/scripts/Build-Bicep.ps1
  src/scripts/Build-Toolkit.ps1
  src/scripts/Deploy-Toolkit.ps1
Labels: Area: ARM, Needs: Review 👀
