Repository microsoft/finops-toolkit, pull requests merged in 2023-12, with the labels that each got.

#475 Fix troubleshooting and resources docs
  docs/finops-hub/README.md
  docs/finops-hub/template.md
  docs/power-bi/setup.md
  docs/resources/README.md
  docs/resources/troubleshooting.md
Labels: Area: Documentation, Needs: Review 👀

#451 Cost optimization workbook - Nov release
  src/workbooks/optimization/AHB/AHB.workbook
  src/workbooks/optimization/Compute/Compute.workbook
  src/workbooks/optimization/Networking/Networking.workbook
  src/workbooks/optimization/Reservations/Reservations.workbook
  src/workbooks/optimization/SavingsPlan/SavingsPlan.workbook
  src/workbooks/optimization/Storage/Storage.workbook
  src/workbooks/optimization/Top10Services/Top10Services.workbook
  src/workbooks/optimization/workbook.json
Labels: Needs: Review 👀, Solution: Workbooks

#459 Add Monitor/Report functions for logging
  src/powershell/Tests/Initialize-Tests.ps1
  src/powershell/Tests/Unit/Initialize-FinOpsHubsDeployment.ps1
  src/scripts/Monitor.ps1
Labels: Needs: Review 👀, Area: PowerShell

#488 Add Test-ShouldProcess to wrap ShouldProcess calls
  src/powershell/Private/Test-ShouldProcess.ps1
  src/powershell/Tests/Unit/Test-ShouldProcess.Tests.ps1
  src/scripts/Test-PowerShell.ps1
Labels: Needs: Review 👀

#489 Standardized localized string names
  src/powershell/FinOpsToolkit.psm1
  src/powershell/Private/New-Directory.ps1
  src/powershell/Private/Save-FinOpsHubTemplate.ps1
  src/powershell/Public/Deploy-FinOpsHub.ps1
  src/powershell/Public/Get-FinOpsCostExport.ps1
  src/powershell/Public/Get-FinOpsHub.ps1
  src/powershell/Public/Get-FinOpsToolkitVersion.ps1
  src/powershell/Public/Invoke-FinOpsSchemaTransform.ps1
  src/powershell/Public/Register-FinOpsHubProviders.ps1
  src/powershell/Public/Remove-FinOpsCostExport.ps1
  src/powershell/Public/Remove-FinOpsHub.ps1
  src/powershell/Tests/Unit/Toolkit.Tests.ps1
  src/powershell/en-US/FinOpsToolkit.strings.psd1
Labels: Needs: Review 👀, Area: PowerShell

#490 Update toolkit icon
  .build/BuildHelper/Build-PsModule.ps1
Labels: Micro PR 🔬, Area: DevOps, Needs: Review 👀

#491 Remove trailing spaces
  .build/BuildHelper/Add-CopyrightHeader.ps1
  .build/build.depends.psd1
  .build/start.ps1
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/🚀-release--internal-only-.md
  SUPPORT.md
  docs/_includes/head.html
  docs/finops-hub/README.md
  src/power-bi/queries/ftk_LoadData.pq
  src/power-bi/queries/ftk_NormalizeSchema.pq
  src/powershell/Private/Split-AzureResourceId.ps1
  src/powershell/Public/ConvertTo-FinOpsSchema.ps1
  src/powershell/Public/Get-FinOpsCostExport.ps1
  src/powershell/Public/Get-FinOpsPricingUnit.ps1
  src/powershell/Public/Get-FinOpsRegion.ps1
  src/powershell/Public/Get-FinOpsResourceType.ps1
  src/powershell/Public/Get-FinOpsService.ps1
  src/powershell/Public/Invoke-FinOpsSchemaTransform.ps1
  src/powershell/Public/Register-FinOpsHubProviders.ps1
  src/powershell/Tests/Integration/FOCUS.Tests.ps1
  src/powershell/Tests/Integration/Hubs.Tests.ps1
  src/powershell/Tests/Integration/New-Directory.Tests.ps1
  src/powershell/Tests/Lint/Lint.Tests.ps1
  src/powershell/Tests/Unit/ConvertTo-FinOpsSchema.Tests.ps1
  src/powershell/Tests/Unit/Deploy-FinOpsHub.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsHub.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsPricingUnit.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsRegion.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsResourceType.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsService.Tests.ps1
  src/powershell/Tests/Unit/Invoke-FinOpsSchemaTransform.Tests.ps1
  src/powershell/Tests/Unit/Register-FinOpsHubProviders.Tests.ps1
  src/powershell/Tests/Unit/Toolkit.Tests.ps1
  src/scripts/Build-Bicep.ps1
  src/scripts/Build-OpenData.ps1
  src/scripts/Build-Toolkit.ps1
  src/scripts/Deploy-Toolkit.ps1
  src/scripts/Invoke-Task.ps1
  src/scripts/Merge-DevBranch.ps1
  src/scripts/Package-Toolkit.ps1
  src/scripts/Publish-Toolkit.ps1
  src/scripts/Test-PowerShell.ps1
  src/scripts/Update-Version.ps1
  src/templates/finops-hub/modules/scripts/Copy-FileToAzureBlob.ps1
  src/templates/finops-hub/modules/scripts/Remove-ManagedIdentity.ps1
  src/templates/finops-hub/modules/scripts/Start-Triggers.ps1
Labels: Needs: Review 👀

#492 Update FinOps hubs tests
  src/powershell/Public/Deploy-FinOpsHub.ps1
  src/powershell/Public/Initialize-FinOpsHubDeployment.ps1
  src/powershell/Tests/Integration/Hubs.Tests.ps1
  src/powershell/Tests/Unit/Deploy-FinOpsHub.Tests.ps1
  src/scripts/Monitor.ps1
Labels: Needs: Review 👀

#496 Return boolean when Remove-FinOpsHub is successful
  docs/changelog.md
  docs/powershell/hubs/Remove-FinOpsHub.md
  src/powershell/Public/Remove-FinOpsHub.ps1
  src/powershell/Tests/Unit/Get-FinOpsResourceType.Tests.ps1
Labels: Needs: Review 👀

#500 Document hubs access requirements
  docs/finops-hub/README.md
Labels: Area: Documentation, Needs: Review 👀, Solution: FinOps hubs

#505 Document all reporting options
  docs/power-bi/README.md
Labels: Area: Documentation, Needs: Review 👀

#507 Call out support options in the docs
  docs/resources/troubleshooting.md
Labels: Area: Documentation, Needs: Review 👀

#508 Document the use of the connector + hubs in Power BI
  docs/power-bi/setup.md
Labels: Area: Documentation, Needs: Review 👀

#509 Document what a scope ID is
  docs/finops-hub/README.md
  src/templates/finops-hub/README.md
Labels: Needs: Review 👀

#510 Fix EA Template app download link
  docs/power-bi/template-app.md
Labels: Area: Documentation, Needs: Review 👀
