Repository microsoft/finops-toolkit, pull requests merged in 2023-09, with the labels that each got.

#284 PR policies based on file paths
  .github/policies/pulls-00-file-paths.yml
Labels: Needs: Review 👀

#290 Update PR policies
  .github/policies/pulls-01-new.yml
  .github/policies/pulls-02-feedback.yml
  .github/policies/pulls-03-respond.yml
  .github/policies/pulls-04-approve.yml
  src/process.md
Labels: Area: DevOps

#265 [DevOps] Doc site – Publish docs to GitHub Pages
  docs/README.md
  docs/_config.yml
  docs/bicep-registry/README.md
  docs/changelog.md
  docs/data-dictionary.md
  docs/data-processing.md
  docs/deploy/README.md
  docs/finops-hub/README.md
  docs/finops-hub/data-dictionary.md
  docs/finops-hub/data-processing.md
  docs/finops-hub/reports/README.md
  docs/finops-hub/reports/commitment-discounts.md
  docs/finops-hub/reports/cost-summary.md
  docs/finops-hub/template.md
  docs/finops-hub/terms.md
  docs/finops-hub/troubleshooting.md
  docs/optimization-workbook/README.md
  docs/terms.md
Labels: Area: Documentation, Needs: Review 👀, Solution: Bicep Registry, Solution: Workbooks, Solution: FinOps hubs

#289 Adding "Services retirement" tab
  src/workbooks/governance/workbook.json
Labels: Needs: Review 👀, Solution: Workbooks

#262 Remove-FinOpsCostExport
  docs/_config.yml
  src/powershell/Public/Remove-FinOpsCostExport.ps1
  src/powershell/en-US/FinOpsToolkit.strings.psd1
Labels: Area: Documentation, Needs: Review 👀, Status: ▶️ Ready, Area: PowerShell

#268 Add managed exports requirements to outputs
  src/templates/finops-hub/main.bicep
  src/templates/finops-hub/modules/hub.bicep
Labels: Area: ARM, Needs: Review 👀, Solution: FinOps hubs

#288 Add telemetry to workbook template
  src/scripts/Build-Toolkit.ps1
  src/workbooks/.scaffold/main.bicep
  src/workbooks/README.md
  src/workbooks/optimization/scaffold.json
Labels: Area: DevOps, Needs: Review 👀, Solution: Workbooks

#317 Add Register-FinOpsProvider
  src/powershell/Public/Register-FinOpsHubProviders.ps1
  src/powershell/en-US/FinOpsToolkit.strings.psd1
Labels: Needs: Review 👀, Area: PowerShell, Solution: FinOps hubs

#319 Issue policy for text containing common words
  .github/policies/issues-00-conventions.yml
Labels: Area: DevOps, Needs: Review 👀

#315 FinOps hubs managed exports docs
  docs/finops-hub/README.md
  docs/finops-hub/data-dictionary.md
  docs/finops-hub/data-processing.md
  docs/finops-hub/reports/README.md
  docs/finops-hub/template.md
  docs/finops-hub/terms.md
  src/templates/finops-hub/main.bicep
  src/templates/finops-hub/modules/hub.bicep
Labels: Area: Documentation, Needs: Review 👀, Solution: FinOps hubs

#313 Update changelog for managed exports
  docs/changelog.md
Labels: Area: Documentation, Needs: Review 👀, Solution: FinOps hubs

#309 Add publish task and fix build
  .build/BuildHelper.psm1
  .build/BuildHelper/Add-CopyrightHeader.ps1
  .build/BuildHelper/Build-PsModule.ps1
  .build/BuildHelper/Start-PesterTest.ps1
  .build/build.depends.psd1
  .build/build.ps1
  .build/start.ps1
  .github/workflows/dev.yml
  .vscode/tasks.json
  src/powershell/Public/Deploy-FinOpsHub.ps1
  src/powershell/Public/Get-FinOpsHub.ps1
  src/powershell/Tests/Lint/Lint.Tests.ps1
  src/scripts/Add-CopyrightHeader.ps1
Labels: Area: DevOps, Needs: Review 👀, Area: PowerShell, Solution: FinOps hubs

#318 Add checklist to PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/policies/pulls-00-checklist.yml
  .github/policies/pulls-00-main-branch.yml
Labels: Area: DevOps, Needs: Review 👀

#312 Add support for all-contributors
  .all-contributorsrc
  .github/policies/pulls-00-file-paths.yml
  README.md
  docs/README.md
Labels: Area: Documentation, Area: DevOps, Needs: Review 👀

#310 Add accessibility alt text bot
  .github/workflows/accessibility-alt-text.yml
Labels: Area: DevOps, Needs: Review 👀

#291 Fix typo in Merge-DevBranch script
  src/scripts/Merge-DevBranch.ps1
Labels: Micro PR 🔬, Area: DevOps, Needs: Review 👀

#330 Rename "exportScopes" to "scopes"
  docs/finops-hub/template.md
  src/powershell/Public/Add-FinOpsHubScope
  src/templates/finops-hub/main.bicep
  src/templates/finops-hub/modules/dataFactory.bicep
  src/templates/finops-hub/modules/hub.bicep
  src/templates/finops-hub/modules/scripts/Copy-FileToAzureBlob.ps1
  src/templates/finops-hub/modules/storage.bicep
Labels: Area: Documentation, Needs: Review 👀, Area: PowerShell, Solution: FinOps hubs

#342 Setup NPM
  package-lock.json
  package.json
Labels: Area: DevOps, Needs: Review 👀

#333 Add region mapping file
  .github/policies/pulls-00-file-paths.yml
  docs/changelog.md
  docs/deploy/README.md
  docs/open-data/README.md
  src/open-data/README.md
  src/open-data/Regions.csv
Labels: Area: Documentation, Area: DevOps, Needs: Review 👀, Solution: Open data

#332 Move dev docs to the wiki
  .github/workflows/wiki-sync.yml
  docs-wiki/CLA.md
  docs-wiki/README.md
  docs-wiki/architecture.md
  docs-wiki/branching.md
  docs-wiki/code.md
  docs-wiki/process.md
  src/README.md
  src/scripts/Init-Repo.ps1
Labels: Area: DevOps, Needs: Review 👀

#325 Remove-FinOpsHub command
  .editorconfig
  src/powershell/Private/Get-HubIdentifier.ps1
  src/powershell/Public/Remove-FinOpsHub.ps1
  src/powershell/en-US/FinOpsToolkit.strings.psd1
Labels: Needs: Review 👀, Area: PowerShell, Solution: FinOps hubs

#346 Fix micro PR label policy
  .github/policies/pulls-00-checklist.yml
Labels: Micro PR 🔬, Area: DevOps, Needs: Review 👀

#347 Assign PRs to reviewers
  .github/policies/pulls-00-file-paths.yml
Labels: Micro PR 🔬, Area: DevOps, Needs: Review 👀

#345 Reduce noise from allcontributors updates for primary contributors
  .all-contributorsrc
  .github/policies/pulls-00-file-paths.yml
Labels: Micro PR 🔬, Needs: Review 👀

#352 Fix doc page for open data
  docs/README.md
  docs/open-data/README.md
Labels: Area: Documentation, Needs: Review 👀, Solution: Open data

#355 Don't include main when syncing feature branches
  src/scripts/Merge-DevBranch.ps1
  src/scripts/README.md
Labels: Area: DevOps, Needs: Review 👀

#354 Update dev docs
  .all-contributorsrc
  docs-wiki/Branching-strategy.md
  docs-wiki/Coding-guidelines.md
  docs-wiki/Contributor-License-Agreement.md
  docs-wiki/Dev-process.md
  docs-wiki/Home.md
  docs-wiki/_Footer.md
  docs-wiki/_Sidebar.md
  docs-wiki/architecture.md
  src/README.md
Labels: Needs: Review 👀

#364 Auto-merge contributor PRs
  .github/policies/pulls-04-approve.yml
Labels: Area: DevOps, Needs: Review 👀

#351 Document 0.1 PowerShell commands
  docs/changelog.md
  docs/deploy/README.md
  docs/open-data/README.md
  docs/powershell/README.md
  docs/powershell/hubs/Deploy-FinOpsHub.md
  docs/powershell/hubs/Get-FinOpsHub.md
  docs/powershell/hubs/README.md
  docs/powershell/toolkit/Get-FinOpsToolkitVersion.md
  docs/powershell/toolkit/README.md
  src/powershell/Public/Deploy-FinOpsHub.ps1
  src/powershell/Public/Get-FinOpsHub.ps1
  src/powershell/Public/Get-FinOpsToolkitVersion.ps1
  src/powershell/README.md
Labels: Needs: Review 👀, Solution: FinOps hubs

#365 Only add contributors when PRs are closed
  .github/policies/pulls-00-file-paths.yml
Labels: Area: DevOps, Needs: Review 👀

#340 Tags by resource bug fix
  src/templates/finops-hub/createUiDefinition.json
  src/templates/finops-hub/main.bicep
  src/templates/finops-hub/modules/dataFactory.bicep
  src/templates/finops-hub/modules/hub.bicep
  src/templates/finops-hub/modules/keyVault.bicep
  src/templates/finops-hub/modules/storage.bicep
Labels: Needs: Review 👀, Solution: FinOps hubs

#368 Add renanalmeidjr for bug reports
  .all-contributorsrc
  README.md
  docs/README.md
Labels: Needs: Review 👀

#370 Add original hubs contributors
  .all-contributorsrc
  README.md
  docs/README.md
Labels: Needs: Review 👀

#283 Add Get-FinOpsCostExport
  src/powershell/Public/Get-FinOpsCostExport.ps1
  src/powershell/en-US/FinOpsToolkit.strings.psd1
Labels: Needs: Review 👀, Area: PowerShell

#373 Auto-label open data issues
  .github/policies/issues-00-conventions.yml
Labels: Micro PR 🔬, Area: DevOps, Needs: Review 👀

#371 Added more apps/modules to Init-Repo.ps1
  src/scripts/Init-Repo.ps1
  src/scripts/README.md
Labels: Area: DevOps, Needs: Review 👀
