Repository microsoft/finops-toolkit, pull requests merged in 2023-10, with the labels that each got.

#348 Add the pricing units open data file
  docs/changelog.md
  docs/open-data/README.md
  src/open-data/PricingUnits.csv
  src/open-data/README.md
Labels: Needs: Review 👀, Solution: Open data

#375 Initialize-FinOpsHubDeployment -Feature
  src/powershell/Public/Initialize-FinOpsHubDeployment.ps1
Labels: Needs: Review 👀, Needs: Attention 👋, Area: PowerShell, Solution: FinOps hubs

#384 Publish to Gallery
  .build/BuildHelper/Build-PsModule.ps1
  .github/workflows/publish.yml
  package-lock.json
  package.json
Labels: Area: DevOps, Status: ▶️ Ready, Area: PowerShell

#381 Added Initilization to Deploy-FinOpsHub before Download
  src/powershell/Public/Deploy-FinOpsHub.ps1
Labels: Needs: Review 👀, Area: PowerShell, Solution: FinOps hubs

#389 Fix PowerShell Publish
  .build/start.ps1
  .github/workflows/publish.yml
Labels: Area: DevOps, Needs: Review 👀

#380 Update settings.json for 0.1
  src/templates/finops-hub/main.bicep
  src/templates/finops-hub/modules/scripts/Copy-FileToAzureBlob.ps1
Labels: Needs: Review 👀, Solution: FinOps hubs

#379 Add npm run build/deploy
  .github/policies/pulls-00-file-paths.yml
  .vscode/tasks.json
  package.json
  src/scripts/Build-Bicep.ps1
  src/scripts/Build-Toolkit.ps1
  src/scripts/Build-Workbook.ps1
  src/scripts/Deploy-Toolkit.ps1
  src/scripts/README.md
Labels: Needs: Review 👀

#392 Publish Parameter Fix
  .build/BuildHelper/Build-PsModule.ps1
  .build/build.ps1
Labels: Area: DevOps, Needs: Review 👀

#393 Custom home title + theme switcher
  docs/_config.yml
  docs/_includes/components/aux_nav.html
  docs/_includes/head.html
  docs/_includes/head_custom.html
  docs/_sass/color_schemes/dark.scss
  docs/_sass/color_schemes/light.scss
  docs/assets/css/just-the-docs-switchable.css
  docs/assets/js/theme-switch.js
  docs/favicon.ico
Labels: Needs: Attention 👋, Status: ⛔ Blocked

#382 Update Governance workbook docs
  docs/governance-workbook/README.md
Labels: Area: Documentation, Status: ▶️ Ready, Solution: Workbooks

#397 Publish-Toolkit updates
  src/scripts/Publish-Toolkit.ps1
Labels: Area: DevOps, Needs: Review 👀

#349 Workbook build templates
  src/scripts/Build-Workbook.ps1
  src/scripts/Publish-Toolkit.ps1
  src/workbooks/optimization/AHB/AHB.workbook
  src/workbooks/optimization/Compute/Compute.workbook
  src/workbooks/optimization/Networking/Networking.workbook
  src/workbooks/optimization/Reservations/Reservations.workbook
  src/workbooks/optimization/Storage/Storage.workbook
  src/workbooks/optimization/workbook.json
Labels: Needs: Review 👀, Solution: Workbooks

#403 Added "troubleshooting" link to the Cost Summary report.
  src/templates/finops-hub/reports/CostSummary.Report/report.json
Labels: Solution: FinOps hubs

#404 Split-AzureResourceId
  src/powershell/Private/Split-AzureResourceId.ps1
  src/powershell/Tests/Unit/Split-AzureResourceId.Tests.ps1
Labels: Needs: Review 👀, Area: PowerShell

#408 Reduce workbook parsing in Build-Workbook
  .github/policies/pulls-00-file-paths.yml
  src/scripts/Build-Workbook.ps1
Labels: Area: DevOps, Needs: Review 👀

#409 Merge workbook feature branch
  .github/policies/pulls-00-file-paths.yml
  src/scripts/Build-Workbook.ps1
  src/scripts/Publish-Toolkit.ps1
  src/workbooks/optimization/AHB/AHB.workbook
  src/workbooks/optimization/Compute/Compute.workbook
  src/workbooks/optimization/Networking/Networking.workbook
  src/workbooks/optimization/Reservations/Reservations.workbook
  src/workbooks/optimization/Storage/Storage.workbook
  src/workbooks/optimization/workbook.json
Labels: Needs: Review 👀

#413 Remove ExportAllColumns parameter
  src/powershell/Public/ConvertTo-FinOpsSchema.ps1
Labels: Needs: Review 👀, Area: PowerShell

#416 ConvertTo-FinOpsSchema columns
  docs/resources/data-dictionary.md
  src/powershell/Public/ConvertTo-FinOpsSchema.ps1
Labels: Needs: Review 👀

#415 Change UsageToPricingRate to PricingBlockSize
  docs/changelog.md
  docs/open-data/README.md
  src/open-data/PricingUnits.csv
  src/open-data/README.md
Labels: Needs: Review 👀

#420 Generate private functions for open data
  package.json
  src/powershell/Private/Get-FinOpsPricingUnitsData.ps1
  src/powershell/Private/Get-FinOpsRegionsData.ps1
  src/powershell/Private/Get-FinOpsServicesData.ps1
  src/powershell/Tests/Unit/Get-FinOpsPricingUnitsData.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsRegionsData.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsServicesData.Tests.ps1
  src/scripts/Build-OpenData.ps1
  src/scripts/README.md
Labels: Needs: Review 👀

#417 Remove managed identities after successful deployment
  src/templates/finops-hub/modules/dataFactory.bicep
  src/templates/finops-hub/modules/scripts/Remove-ManagedIdentity.ps1
  src/templates/finops-hub/modules/storage.bicep
Labels: Needs: Review 👀, Solution: FinOps hubs

#421 Rename open data commands to distinguish from public commands
  src/powershell/Private/Get-OpenDataPricingUnits.ps1
  src/powershell/Private/Get-OpenDataRegions.ps1
  src/powershell/Private/Get-OpenDataServices.ps1
  src/powershell/Tests/Unit/Get-OpenDataPricingUnits.Tests.ps1
  src/powershell/Tests/Unit/Get-OpenDataRegions.Tests.ps1
  src/powershell/Tests/Unit/Get-OpenDataServices.Tests.ps1
  src/scripts/Build-OpenData.ps1
Labels: Needs: Review 👀

#422 Fix Split-AzureResourceId tests
  src/powershell/Tests/Unit/Split-AzureResourceId.Tests.ps1
Labels: Needs: Review 👀, Area: PowerShell

#423 Add Get-FinOpsSchema* functions for open data sets
  src/powershell/Public/Get-FinOpsSchemaPricingUnit.ps1
  src/powershell/Public/Get-FinOpsSchemaRegion.ps1
  src/powershell/Public/Get-FinOpsSchemaService.ps1
  src/powershell/Tests/Unit/Get-FinOpsSchemaPricingUnit.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsSchemaRegion.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsSchemaService.Tests.ps1
Labels: Needs: Review 👀, Area: PowerShell

#426 Workbook v2
  src/scripts/Build-Workbook.ps1
Labels: Area: DevOps, Needs: Review 👀, Solution: Workbooks

#425 Integrate with data lookups
  docs/changelog.md
  docs/powershell/data/Get-FinOpsPricingUnit.md
  docs/powershell/data/Get-FinOpsRegion.md
  docs/powershell/data/Get-FinOpsService.md
  docs/powershell/data/README.md
  docs/powershell/focus/ConvertTo-FinOpsSchema.md
  docs/powershell/focus/Invoke-FinOpsSchemaTransform.md
  docs/powershell/focus/README.md
  src/powershell/Private/Split-AzureResourceId.ps1
  src/powershell/Public/ConvertTo-FinOpsSchema.ps1
  src/powershell/Public/Get-FinOpsPricingUnit.ps1
  src/powershell/Public/Get-FinOpsRegion.ps1
  src/powershell/Public/Get-FinOpsService.ps1
  src/powershell/Public/Invoke-FinOpsSchemaTransform.ps1
  src/powershell/Tests/Unit/ConvertTo-FinOpsSchema.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsPricingUnit.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsRegion.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsService.Tests.ps1
Labels: Needs: Review 👀, Area: PowerShell

#412 Add new deliverables to Package-Toolkit
  .build/BuildHelper/Update-Version.ps1
  .build/build.ps1
  package.json
  src/scripts/Get-Version.ps1
  src/scripts/Package-Toolkit.ps1
  src/scripts/Update-Version.ps1
Labels: Needs: Review 👀, Area: PowerShell

#428 Features/powershell
  .editorconfig
  .github/workflows/dev.yml
  .vscode/settings.json
  docs/_config.yml
  src/bicep-registry/tag-inheritance/README.md
  src/bicep-registry/tag-inheritance/main.bicep
  src/bicep-registry/tag-inheritance/scaffold.json
  src/bicep-registry/tag-inheritance/test/main.test.bicep
  src/powershell/Private/Get-HubIdentifier.ps1
  src/powershell/Public/Deploy-FinOpsHub.ps1
  src/powershell/Public/Get-FinOpsCostExport.ps1
  src/powershell/Public/Initialize-FinOpsHubDeployment.ps1
  src/powershell/Public/Register-FinOpsHubProviders.ps1
  src/powershell/Public/Remove-FinOpsCostExport.ps1
  src/powershell/Public/Remove-FinOpsHub.ps1
  src/powershell/en-US/FinOpsToolkit.strings.psd1
Labels: Needs: Review 👀

#433 Added PS docs
  docs/powershell/cost/Get-FinOpsCostExport.md
  docs/powershell/cost/Remove-FinOpsCostExport.md
  docs/powershell/hubs/Initialize-FinOpsHubDeployment.md
  docs/powershell/hubs/Register-FinOpsHubProviders.md
  docs/powershell/hubs/Remove-FinOpsHub.md
Labels: Area: Documentation, Needs: Review 👀, Area: PowerShell

#435 Remove ternary operators (to support Windows PowerShell)
  src/powershell/Public/ConvertTo-FinOpsSchema.ps1
  src/powershell/Public/Get-FinOpsRegion.ps1
  src/powershell/Public/Get-FinOpsService.ps1
Labels: Needs: Review 👀, Area: PowerShell

#436 Add build/tests PS scripts
  src/scripts/Build-PowerShell.ps1
  src/scripts/Test-PowerShell.ps1
Labels: Area: DevOps, Needs: Review 👀

#438 Added list of roles needed to deploy Hub
  docs/finops-hub/template.md
Labels: Area: Documentation, Needs: Review 👀, Solution: FinOps hubs

#441 Fix Deploy-FinOpsHub typo + test fixes (Fixes #440)
  docs-wiki/Release-process.md
  src/powershell/Private/Save-FinOpsHubTemplate.ps1
  src/powershell/Public/Deploy-FinOpsHub.ps1
  src/powershell/Public/Get-FinOpsHub.ps1
  src/powershell/Public/Initialize-FinOpsHubDeployment.ps1
  src/powershell/Tests/Unit/Deploy-FinOpsHub.Tests.ps1
  src/powershell/Tests/Unit/FinOpsToolkit.Tests.ps1
  src/powershell/Tests/Unit/Get-FinOpsHub.Tests.ps1
  src/scripts/Package-Toolkit.ps1
  src/scripts/Test-PowerShell.ps1
Labels: Needs: Review 👀

#314 Update deployment support for Azure China
  docs/finops-hub/README.md
  src/templates/finops-hub/modules/dataFactory.bicep
  src/templates/finops-hub/modules/keyVault.bicep
  src/templates/finops-hub/modules/storage.bicep
Labels: Area: Documentation, Needs: Review 👀, Solution: FinOps hubs

#424 Added New-FinOpsCostExport
  src/powershell/Private/Invoke-Rest.ps1
  src/powershell/Public/New-FinOpsCostExport.ps1
Labels: Needs: Review 👀, Area: PowerShell

#446 Fix Pester GitHub action
  .build/BuildHelper/Start-PesterTest.ps1
Labels: Area: DevOps, Needs: Review 👀

#444 Add a summary to the Test-PowerShell script
  src/scripts/README.md
  src/scripts/Test-PowerShell.ps1
Labels: Area: DevOps, Needs: Review 👀

#443 Separate integration tests
  .build/BuildHelper/Start-PesterTest.ps1
  src/powershell/Public/ConvertTo-FinOpsSchema.ps1
  src/powershell/README.md
  src/powershell/Tests/Initialize-Tests.ps1
  src/powershell/Tests/Integration/Get-FinOpsToolkitVersion.Tests.ps1
  src/powershell/Tests/Integration/Invoke-FinOpsSchemaTransform.Tests.ps1
  src/powershell/Tests/Integration/New-Directory.Tests.ps1
  src/powershell/Tests/Unit/ConvertTo-FinOpsSchema.Tests.ps1
  src/powershell/Tests/Unit/Deploy-FinOpsHub.Tests.ps1
  src/powershell/Tests/Unit/FinOpsToolkit.Tests.ps1
  src/powershell/Tests/Unit/Invoke-FinOpsSchemaTransform.Tests.ps1
  src/powershell/Tests/assets/EA_ActualCost_Small.csv
  src/powershell/Tests/assets/EA_AmortizedCost_Small.csv
  src/powershell/Tests/assets/EA_NoRows.csv
Labels: Needs: Review 👀
