Repository microsoft/finops-toolkit, pull requests merged in 2023-02, with the labels that each got.

#5 Power BI on raw CM exports spec
  .vscode/settings.json
  docs/README.md
  docs/deploy/README.md
  docs/reports/README.md
  docs/reports/commitment-discounts.md
  docs/reports/cost-summary.md
  docs/reports/terms.md
  docs/templates/README.md
  docs/templates/finops-hub-with-exports.md
  docs/templates/finops-hub.md
  docs/templates/modules/README.md
  docs/templates/modules/export.md
  docs/templates/modules/hub.md
Labels: Area: Documentation, Type: Feature 💎, Status: ⏸️ Pending review

#21 Create finops-hub template with storage account
  .vscode/settings.json
  src/README.md
  src/modules/Microsoft.Storage/storageAccounts/blobServices/containers/deploy.bicep
  src/modules/Microsoft.Storage/storageAccounts/blobServices/deploy.bicep
  src/modules/Microsoft.Storage/storageAccounts/deploy.bicep
  src/modules/README.md
  src/modules/hub.bicep
  src/scripts/Deploy-Toolkit.ps1
  src/scripts/Init-Repo.ps1
  src/scripts/README.md
  src/templates/finops-hub/main.bicep
Labels: Type: Feature 💎, Status: ⏸️ Pending review, Area: ARM

#48 Flesh out doc landing page
  .vscode/settings.json
  docs/README.md
  docs/deploy/README.md
  docs/reports/README.md
  docs/reports/commitment-discounts.md
  docs/reports/cost-summary.md
Labels: Area: Documentation

#52 Document telemetry
  .vscode/settings.json
  README.md
  src/modules/README.md
  src/modules/hub.bicep
Labels: Area: Documentation, Area: ARM

#68 Spec: Documented the branching strategy
  src/README.md
  src/branching.md
Labels: Area: GitHub, Needs: Review 👀

#62 Spec: Update docs based on revised plans
  docs/README.md
  docs/templates/README.md
  docs/templates/finops-hub-with-exports.md
  docs/templates/finops-hub.md
  docs/templates/modules/hub.md
  src/architecture.md
  src/templates/README.md
Labels: Area: Data factory, Area: ARM, Needs: Review 👀

#70 Add CARML AKV Modules
  src/modules/Microsoft.KeyVault/vaults/.bicep/nested_roleAssignments.bicep
  src/modules/Microsoft.KeyVault/vaults/accessPolicies/deploy.bicep
  src/modules/Microsoft.KeyVault/vaults/accessPolicies/readme.md
  src/modules/Microsoft.KeyVault/vaults/accessPolicies/version.json
  src/modules/Microsoft.KeyVault/vaults/deploy.bicep
  src/modules/Microsoft.KeyVault/vaults/keys/.bicep/nested_roleAssignments.bicep
  src/modules/Microsoft.KeyVault/vaults/keys/deploy.bicep
  src/modules/Microsoft.KeyVault/vaults/keys/readme.md
  src/modules/Microsoft.KeyVault/vaults/keys/version.json
  src/modules/Microsoft.KeyVault/vaults/readme.md
  src/modules/Microsoft.KeyVault/vaults/secrets/.bicep/nested_roleAssignments.bicep
  src/modules/Microsoft.KeyVault/vaults/secrets/deploy.bicep
  src/modules/Microsoft.KeyVault/vaults/secrets/readme.md
  src/modules/Microsoft.KeyVault/vaults/secrets/version.json
  src/modules/Microsoft.KeyVault/vaults/version.json
Labels: Area: ARM
