Repository microsoft/finops-toolkit, pull requests merged in 2024-01, with the labels that each got.

#520 Fixed FOCUS sample file
  src/sample-data/EA-Cost-FOCUS.csv
Labels: Needs: Review 👀

#521 Deprecate FOCUS PowerShell commands
  docs/changelog.md
  docs/powershell/focus/ConvertTo-FinOpsSchema.md
  docs/powershell/focus/Invoke-FinOpsSchemaTransform.md
  src/powershell/Public/ConvertTo-FinOpsSchema.ps1
  src/powershell/Public/Invoke-FinOpsSchemaTransform.ps1
Labels: Needs: Review 👀

#498 Add -AsDotNetVersion option to the Get-Version script
  src/scripts/Get-Version.ps1
Labels: Area: DevOps, Needs: Review 👀

#511 Service library template
  docs/services/.template/template.md
  docs/services/README.md
  docs/services/compute/README.md
  docs/services/compute/virtual-machines.md
Labels: Area: Documentation, Needs: Review 👀

#514 Cost optimization workbook dec release
  src/workbooks/optimization/Compute/Compute.workbook
  src/workbooks/optimization/CostOptimization.workbook
  src/workbooks/optimization/Networking/Networking.workbook
  src/workbooks/optimization/Storage/Storage.workbook
  src/workbooks/optimization/Top10Services/Top10Services.workbook
Labels: Needs: Review 👀, Solution: Workbooks

#336 Use yyyyMM folder names
  src/templates/finops-hub/modules/dataFactory.bicep
Labels: Micro PR 🔬, Area: Data factory, Needs: Review 👀, Solution: FinOps hubs

#337 Delete old triggers/pipelines
  src/templates/finops-hub/modules/dataFactory.bicep
  src/templates/finops-hub/modules/scripts/Remove-OldResources.ps1
Labels: Area: Data factory, Needs: Review 👀, Solution: FinOps hubs

#339 Backfill recent months first
  src/templates/finops-hub/modules/dataFactory.bicep
Labels: Micro PR 🔬, Area: Data factory, Needs: Review 👀, Solution: FinOps hubs

#526 Update version to 0.1.2
  package-lock.json
  package.json
Labels: Area: DevOps, Needs: Review 👀

#531 Added Workbook change log
  docs/changelog.md
Labels: Area: Documentation, Needs: Review 👀

#539 Add one-time export test
  docs/powershell/cost/Get-FinOpsCostExport.md
  docs/powershell/cost/New-FinOpsCostExport.md
  src/powershell/Public/New-FinOpsCostExport.ps1
  src/powershell/Tests/Integration/CostExports.Tests.ps1
  src/sample-data/EA-Cost-Amortized.csv
Labels: Needs: Review 👀

#540 FOCUS export folder path has a missing folder
  src/templates/finops-hub/modules/dataFactory.bicep
  src/templates/finops-hub/modules/scripts/Remove-ManagedIdentity.ps1
Labels: Needs: Review 👀, Solution: FinOps hubs

#545 Add explicit types for FOCUS columns
  src/templates/finops-hub/modules/dataFactory.bicep
Labels: Needs: Review 👀, Solution: FinOps hubs

#538 Unique ID in FOCUS
  docs/focus/README.md
Labels: Area: Documentation, Needs: Review 👀

#549 Version 0.2 cleanup
  docs/changelog.md
  package-lock.json
  package.json
  src/scripts/Publish-Toolkit.ps1
  src/scripts/README.md
  src/templates/finops-hub/modules/scripts/Remove-OldResources.ps1
  src/templates/finops-hub/modules/storage.bicep
  src/workbooks/optimization/scaffold.json
Labels: Needs: Review 👀

#552 Update release process, Package-Toolkit script, and doc version
  docs-wiki/Release-process.md
  docs/_includes/version.txt
  src/scripts/Package-Toolkit.ps1
Labels: Needs: Review 👀

#533 VM guidance per capability - first release
  docs/services/compute/virtual-machines.md
Labels: Area: Documentation, Needs: Review 👀
