Repository microsoft/finops-toolkit, pull requests merged in 2024-02, with the labels that each got.

#574 Fix ADF errors in Hubs 0.2
  docs/_includes/version.txt
  docs/changelog.md
  docs/deploy/finops-hub-0.2.1-rc.2.json
  docs/deploy/finops-hub-latest.json
  docs/deploy/governance-workbook-0.2.1-rc.2.json
  docs/deploy/governance-workbook-latest.json
  docs/deploy/optimization-workbook-0.2.1-rc.2.json
  docs/deploy/optimization-workbook-latest.json
  docs/finops-hub/README.md
  docs/governance-workbook/README.md
  docs/optimization-workbook/README.md
  package-lock.json
  package.json
  src/scripts/Build-Toolkit.ps1
  src/scripts/Package-Toolkit.ps1
  src/scripts/Update-Version.ps1
  src/templates/finops-hub/modules/dataFactory.bicep
Labels: Needs: Review 👀, Solution: FinOps hubs

#580 Documented known issues with the connector report
  docs/power-bi/connector.md
Labels: Area: Documentation, Needs: Review 👀

#587 Don't build resource types unless requested in Build-OpenData
  src/scripts/Build-OpenData.ps1
Labels: Area: DevOps, Needs: Review 👀

#589 Update all version numbers in Update-Version
  docs/README.md
  docs/_includes/ftkver.txt
  docs/powershell/hubs/Deploy-FinOpsHub.md
  src/powershell/Private/Get-VersionNumber.ps1
  src/powershell/Private/Invoke-Rest.ps1
  src/powershell/Tests/Unit/Get-VersionNumber.Tests.ps1
  src/scripts/Build-Toolkit.ps1
  src/scripts/Get-Version.ps1
  src/scripts/Package-Toolkit.ps1
  src/scripts/README.md
  src/scripts/Test-PowerShell.ps1
  src/scripts/Update-Version.ps1
  src/templates/finops-hub/modules/ftkver.txt
  src/templates/finops-hub/modules/hub.bicep
  src/templates/finops-hub/modules/storage.bicep
  src/templates/finops-hub/modules/version.txt
  src/workbooks/.scaffold/ftkver.txt
  src/workbooks/.scaffold/main.bicep
  src/workbooks/.scaffold/version.txt
Labels: Area: DevOps, Needs: Review 👀

#590 Add Pester to Init-Repo
  src/scripts/Init-Repo.ps1
  src/scripts/README.md
Labels: Area: DevOps, Needs: Review 👀

#592 Fix broken links to Open data Regions and Resource types
  docs/_includes/tools.md
Labels: Area: Documentation, Needs: Review 👀

#579 Document hubs storage folder hierarchy
  docs/finops-hub/data-processing.md
Labels: Area: Documentation, Needs: Review 👀, Solution: FinOps hubs

#591 Add new troubleshooting steps
  docs/resources/troubleshooting.md
Labels: Area: Documentation, Needs: Review 👀

#599 Fix x_SkuTerm column values
  docs/changelog.md
  src/power-bi/CostSummary.Report/.pbi/localSettings.json
  src/power-bi/CostSummary.Report/report.json
  src/power-bi/Shared.Dataset/model.bim
  src/power-bi/queries/ftk_CostDetails.pq
Labels: Area: Power BI, Needs: Review 👀

#582 Add ServiceModel to Services.csv
  src/open-data/README.md
  src/open-data/Services.csv
Labels: Needs: Review 👀, Solution: Open data

#608 Clean up Deploy-FinOpsHub examples
  docs/powershell/hubs/Deploy-FinOpsHub.md
  src/powershell/Private/Save-FinOpsHubTemplate.ps1
  src/powershell/Public/Deploy-FinOpsHub.ps1
  src/powershell/Public/Initialize-FinOpsHubDeployment.ps1
  src/powershell/Tests/Unit/Initialize-FinOpsHubDeployment.Tests.ps1
  src/powershell/Tests/Unit/Initialize-FinOpsHubsDeployment.ps1
  src/powershell/Tests/Unit/Save-FinOpsHubTemplate.Tests.ps1
  src/powershell/en-US/FinOpsToolkit.strings.psd1
Labels: Needs: Review 👀, Area: PowerShell

#606 Start-FinOpsCostExport -Backfill -StartDate -EndDate
  docs/changelog.md
  src/powershell/Public/New-FinOpsCostExport.ps1
  src/powershell/Public/Start-FinOpsCostExport.ps1
  src/powershell/Tests/Unit/New-FinOpsCostExport.Tests.ps1
  src/powershell/Tests/Unit/Start-FinOpsCostExport.Tests.ps1
Labels: Needs: Review 👀

#618 Azure Governance workbook updates (managed disks usages, api version update and general improvements)
  src/workbooks/governance/workbook.json
Labels: Needs: Review 👀, Solution: Workbooks

#611 Update PowerShell for service model
  docs/changelog.md
  docs/powershell/data/Get-FinOpsService.md
  src/open-data/Services.csv
  src/powershell/Private/Get-OpenDataService.ps1
  src/powershell/Public/Get-FinOpsService.ps1
  src/powershell/Tests/Unit/Get-FinOpsService.Tests.ps1
Labels: Needs: Review 👀
