Repository microsoft/finops-toolkit, pull requests merged in 2024-06, with the labels that each got.

#719 Document how to build and test tools
  docs-wiki/Build-and-test.md
  docs-wiki/Dev-process.md
  docs-wiki/_Sidebar.md
  src/bicep-registry/README.md
Labels: Area: Documentation, Needs: Review 👀

#713 Document FinOps toolkit governance model
  .github/fabricbot.json
  docs-wiki/About.md
  docs-wiki/Advisory-council.md
  docs-wiki/Governing-board.md
  docs-wiki/Home.md
  docs-wiki/Roadmap.md
  docs-wiki/Support-escalations.md
  docs-wiki/_Sidebar.md
Labels: Area: Documentation, Needs: Review 👀

#571 Update data factory pipeline to FOCUS exports
  src/templates/finops-hub/modules/dataFactory.bicep
  src/templates/finops-hub/modules/hub.bicep
  src/templates/finops-hub/modules/scripts/Copy-FileToAzureBlob.ps1
  src/templates/finops-hub/modules/storage.bicep
  src/templates/finops-hub/schema/focuscost_1.0-preview(v1).json
Labels: Area: Data factory, Status: ▶️ Ready, Solution: FinOps hubs

#737 Parameters to sort based on the update time and disk size for idle disks
  src/workbooks/optimization/Storage/Storage.workbook
Labels: Needs: Review 👀, Solution: Workbooks

#712 Added FOCUS 1.0-preview(v1) metadata
  .gitattributes
  docs/_docs/focus/metadata.md
  docs/_reporting/data/README.md
  docs/_resources/changelog.md
  src/open-data/dataset-examples/EA-Cost-Actual.csv
  src/open-data/dataset-examples/EA-Cost-Amortized.csv
  src/open-data/dataset-examples/EA-Cost-FOCUS.csv
  src/open-data/dataset-examples/EA-Prices.csv
  src/open-data/dataset-examples/EA-Reservations-Details.csv
  src/open-data/dataset-examples/EA-Reservations-Recommendations.csv
  src/open-data/dataset-examples/EA-Reservations-Transactions.csv
  src/open-data/dataset-metadata/FocusCost_1.0-preview(v1).json
  src/scripts/Package-Toolkit.ps1
Labels: Area: Documentation, Needs: Review 👀, Solution: Open data

#683 FX2024 Domain & Capabilities update / Optimize / Cloud Sustainability
  docs/_docs/framework/capabilities/manage/intersecting-disciplines.md
  docs/_docs/framework/capabilities/optimize/sustainability.md
Labels: Area: Documentation, Needs: Review 👀

#744 Update roadmap
  docs-wiki/Roadmap.md
Labels: Area: Documentation, Needs: Review 👀

#646 FX2024 Domain & Capabilities update /Quantify Business Value / Benchmarking
  docs/_docs/framework/capabilities/quantify/benchmarking.md
Labels: Area: Documentation, Needs: Review 👀, Needs: Attention 👋

#707 Create finops-assessment capability
  docs/_docs/framework/capabilities/manage/finops-assessment.md
Labels: Area: Documentation, Needs: Review 👀

#746 Update ETL pipeline to support better date filtering in PBI.
  src/power-bi/queries/ftk_DatetimeToJulianDate.pq
  src/power-bi/queries/ftk_ImpalaToJulianDate.pq
  src/power-bi/queries/ftk_Metadata.pq
  src/templates/finops-hub/modules/dataFactory.bicep
Labels: Status: ▶️ Ready, Solution: FinOps hubs

#751 Add FinOps Practice Operations doc
  docs/_docs/framework/capabilities/manage/practice-ops.md
Labels: Area: Documentation, Needs: Review 👀

#750 Cost Optimization Workbook (COW)- May Update
  docs/_resources/changelog.md
  src/workbooks/optimization/CostOptimization.workbook
  src/workbooks/optimization/Networking/Networking.workbook
  src/workbooks/optimization/Reservations Preview/ReservationsPreview.workbook
  src/workbooks/optimization/Sustainability/Sustainability.workbook
  src/workbooks/optimization/Top10Services/Top10Services.workbook
Labels: Needs: Review 👀

#748 Update export tests
  src/powershell/Tests/Integration/CostExports.Tests.ps1
Labels: Needs: Review 👀, Area: PowerShell

#740 Edit pass on docs articles
  docs-mslearn/conduct-an-iteration.md
  docs-mslearn/framework/manage/culture.md
  docs-mslearn/framework/manage/education.md
  docs-mslearn/framework/manage/intersecting-disciplines.md
  docs-mslearn/framework/manage/invoicing-chargeback.md
  docs-mslearn/framework/manage/onboarding.md
  docs-mslearn/framework/manage/policy.md
  docs-mslearn/framework/manage/structure.md
  docs-mslearn/framework/optimize/commitment-discounts.md
  docs-mslearn/framework/optimize/utilization-efficiency.md
  docs-mslearn/framework/optimize/workloads.md
  docs-mslearn/framework/quantify/budgeting.md
  docs-mslearn/framework/quantify/forecasting.md
  docs-mslearn/framework/quantify/unit-economics.md
  docs-mslearn/framework/understand/allocation.md
  docs-mslearn/framework/understand/anomalies.md
  docs-mslearn/framework/understand/ingestion.md
  docs-mslearn/framework/understand/reporting.md
  docs-mslearn/framework/understand/shared-cost.md
  docs-mslearn/overview.md
Labels: Area: Documentation, Status: ▶️ Ready

#747 Spelling + grammar fixes
  docs-wiki/Support-escalations.md
Labels: Status: ▶️ Ready

#716 added changes to register event grid provider
  src/templates/finops-hub/modules/hub.bicep
Labels: Status: ▶️ Ready, Solution: FinOps hubs

#754 FinOps Framework 2024 updates
  .vscode/settings.json
  docs/_docs/conduct-an-iteration.md
  docs/_docs/framework/README.md
  docs/_docs/framework/capabilities/README.md
  docs/_docs/framework/capabilities/manage/README.md
  docs/_docs/framework/capabilities/manage/assessment.md
  docs/_docs/framework/capabilities/manage/culture.md
  docs/_docs/framework/capabilities/manage/education.md
  docs/_docs/framework/capabilities/manage/invoicing-chargeback.md
  docs/_docs/framework/capabilities/manage/operations.md
  docs/_docs/framework/capabilities/manage/policy.md
  docs/_docs/framework/capabilities/manage/structure.md
  docs/_docs/framework/capabilities/optimize/README.md
  docs/_docs/framework/capabilities/optimize/rates.md
  docs/_docs/framework/capabilities/optimize/sustainability.md
  docs/_docs/framework/capabilities/optimize/workloads.md
  docs/_docs/framework/capabilities/quantify/README.md
  docs/_docs/framework/capabilities/quantify/benchmarking.md
  docs/_docs/framework/capabilities/quantify/forecasting.md
  docs/_docs/framework/capabilities/understand/README.md
  docs/_docs/framework/capabilities/understand/allocation.md
  docs/_docs/framework/capabilities/understand/anomalies.md
  docs/_docs/framework/capabilities/understand/ingestion.md
  docs/_docs/framework/capabilities/understand/reporting.md
  docs/_docs/what-is-finops.md
  docs/_reporting/power-bi/README.md
  docs/_resources/changelog.md
  docs/_resources/data-dictionary.md
  docs/_resources/terms.md
  docs/_workbooks/optimization-workbook/cost-optimization-workbook.md
Labels: Area: Documentation, Needs: Review 👀

#756 FinOps Framework 2024 updates
  .vscode/settings.json
  docs/_docs/conduct-an-iteration.md
  docs/_docs/framework/README.md
  docs/_docs/framework/capabilities/README.md
  docs/_docs/framework/capabilities/manage/README.md
  docs/_docs/framework/capabilities/manage/assessment.md
  docs/_docs/framework/capabilities/manage/culture.md
  docs/_docs/framework/capabilities/manage/education.md
  docs/_docs/framework/capabilities/manage/intersecting-disciplines.md
  docs/_docs/framework/capabilities/manage/invoicing-chargeback.md
  docs/_docs/framework/capabilities/manage/operations.md
  docs/_docs/framework/capabilities/manage/policy.md
  docs/_docs/framework/capabilities/manage/structure.md
  docs/_docs/framework/capabilities/manage/tools-and-services.md
  docs/_docs/framework/capabilities/optimize/README.md
  docs/_docs/framework/capabilities/optimize/architecting.md
  docs/_docs/framework/capabilities/optimize/licensing.md
  docs/_docs/framework/capabilities/optimize/rate-optimization.md
  docs/_docs/framework/capabilities/optimize/rates.md
  docs/_docs/framework/capabilities/optimize/sustainability.md
  docs/_docs/framework/capabilities/optimize/utilization-efficiency.md
  docs/_docs/framework/capabilities/optimize/workloads.md
  docs/_docs/framework/capabilities/optimize/workloads.tobedeleted
  docs/_docs/framework/capabilities/quantify/README.md
  docs/_docs/framework/capabilities/quantify/benchmarking.md
  docs/_docs/framework/capabilities/quantify/budgeting.md
  docs/_docs/framework/capabilities/quantify/forecasting.md
  docs/_docs/framework/capabilities/quantify/planning.md
  docs/_docs/framework/capabilities/quantify/unit-economics.md
  docs/_docs/framework/capabilities/understand/README.md
  docs/_docs/framework/capabilities/understand/allocation.md
  docs/_docs/framework/capabilities/understand/anomalies.md
  docs/_docs/framework/capabilities/understand/ingestion.md
  docs/_docs/framework/capabilities/understand/reporting.md
  docs/_docs/framework/capabilities/understand/shared-cost.toberemoved
  docs/_docs/what-is-finops.md
  docs/_reporting/power-bi/README.md
  docs/_resources/changelog.md
  docs/_resources/data-dictionary.md
  docs/_resources/terms.md
  docs/_workbooks/optimization-workbook/cost-optimization-workbook.md
Labels: Needs: Review 👀

#738 Merge Exports branch to Dev Branch
  docs-wiki/Branching-strategy.md
  docs/_reporting/hubs/README.md
  docs/_reporting/hubs/configure-scopes.md
  docs/_reporting/hubs/data-processing.md
  docs/_reporting/hubs/template.md
  src/README.md
  src/bicep-registry/README.md
  src/open-data/dataset-examples/EA-Cost-FOCUS.csv
  src/power-bi/DataIngestion.Report/report.json
  src/power-bi/Shared.Dataset/model.bim
  src/power-bi/queries/ftk_DatetimeToJulianDate.pq
  src/power-bi/queries/ftk_ImpalaToJulianDate.pq
  src/power-bi/queries/ftk_Metadata.pq
  src/powershell/Public/Add-FinOpsHubScope
  src/powershell/Public/Add-FinOpsHubScope.ps1
  src/powershell/Public/Add-FinOpsServicePrincipal
  src/powershell/Public/Add-FinOpsServicePrincipal.ps1
  src/powershell/en-US/FinOpsToolkit.strings.psd1
  src/templates/finops-hub/main.bicep
  src/templates/finops-hub/modules/azuretimezones.bicep
  src/templates/finops-hub/modules/dataFactory.bicep
  src/templates/finops-hub/modules/hub.bicep
  src/templates/finops-hub/modules/keyVault.bicep
  src/templates/finops-hub/modules/scripts/Copy-FileToAzureBlob.ps1
  src/templates/finops-hub/modules/scripts/Remove-OldResources.ps1
  src/templates/finops-hub/modules/scripts/Start-Triggers.ps1
  src/templates/finops-hub/modules/storage.bicep
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/CustomVisuals/HierarchySlicer1458836712039/package.json
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/CustomVisuals/HierarchySlicer1458836712039/resources/HierarchySlicer1458836712039.pbiviz.json
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/CustomVisuals/hierarchyChartByAkvelon6F792A8745784877BCD8F4ACA5AD4207/package.json
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/CustomVisuals/hierarchyChartByAkvelon6F792A8745784877BCD8F4ACA5AD4207/resources/hierarchyChartByAkvelon6F792A8745784877BCD8F4ACA5AD4207.pbiviz.json
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/RegisteredResources/ACMLearnMore3455599414129229.png
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/RegisteredResources/AzureCost_HeroAdjustment-Resize2x5775843843846507.png
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/RegisteredResources/Ibiza_Data_Visualization_Theme4744941034384995.json
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/RegisteredResources/LearnMore7090101546343053.png
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/RegisteredResources/feedback3410273840221807.png
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/SharedResources/BaseThemes/CY19SU06.json
  src/templates/finops-hub/schema/README.md
  src/templates/finops-hub/schema/focuscost_1.0-preview(v1).json
  src/templates/finops-hub/schema/schema_ea_normalized.json
  src/templates/finops-hub/schema/schema_mca_normalized.json
Labels: Needs: Review 👀, Solution: FinOps hubs

#758 Framework 2024 cleanup
  docs/_docs/framework/capabilities/optimize/workloads.md
  docs/_docs/framework/capabilities/optimize/workloads.tobedeleted
  docs/_docs/framework/capabilities/understand/allocation.md
  docs/_docs/framework/capabilities/understand/shared-cost.toberemoved
Labels: Area: Documentation, Needs: Review 👀

#760 Update FTK version
  docs/_includes/ftkver.txt
  package-lock.json
  package.json
  src/powershell/Private/Get-VersionNumber.ps1
  src/templates/finops-hub/modules/ftkver.txt
  src/workbooks/.scaffold/ftkver.txt
Labels: Needs: Review 👀

#759 Update sample data
  docs/_docs/focus/metadata.md
  docs/_reporting/data/README.md
  docs/_resources/changelog.md
  src/open-data/dataset-examples/EA-Cost-Actual.csv
  src/open-data/dataset-examples/EA-Cost-Amortized.csv
  src/open-data/dataset-examples/EA-Cost-FOCUS.csv
  src/open-data/dataset-examples/EA-Cost-FOCUS_1.0-preview.csv
  src/open-data/dataset-examples/EA-Cost-FOCUS_1.0.csv
  src/open-data/dataset-examples/EA-Prices.csv
  src/open-data/dataset-examples/EA-Reservations-Details.csv
  src/open-data/dataset-examples/EA-Reservations-Recommendations.csv
  src/open-data/dataset-examples/EA-Reservations-Transactions.csv
Labels: Needs: Review 👀, Solution: Open data

#769 Fix broken links in docs
  docs/_docs/framework/capabilities/manage/assessment.md
  docs/_docs/framework/capabilities/manage/education.md
  docs/_docs/framework/capabilities/manage/operations.md
  docs/_docs/framework/capabilities/manage/tools-and-services.md
  docs/_docs/framework/capabilities/optimize/architecting.md
  docs/_docs/framework/capabilities/optimize/rate-optimization.md
  docs/_docs/framework/capabilities/optimize/utilization-efficiency.md
  docs/_docs/framework/capabilities/quantify/benchmarking.md
  docs/_docs/framework/capabilities/quantify/unit-economics.md
  docs/_docs/framework/capabilities/understand/reporting.md
Labels: Area: Documentation, Needs: Review 👀
