Repository microsoft/finops-toolkit, pull requests merged in 2024-04, with the labels that each got.

#642 FX2024 Domain & Capabilities update / Understand cloud usage and cost
  docs/_docs/framework/capabilities/quantify/budgeting.md
  docs/_docs/framework/capabilities/quantify/unit-economics.md
  docs/_docs/framework/capabilities/understand/allocation.md
  docs/_docs/framework/capabilities/understand/ingestion.md
  docs/_docs/framework/capabilities/understand/reporting.md
  docs/_docs/framework/capabilities/understand/shared-cost.toberemoved
Labels: Area: Documentation, Needs: Review 👀

#680 FX2024 Domain & Capabilities update / Optimize / Licensing + SaaS
  docs/_docs/framework/capabilities/optimize/licensing.md
Labels: Area: Documentation, Needs: Review 👀

#676 FX2024 Domain & Capabilities update / Optimize / Architecting for cloud
  docs/_docs/framework/capabilities/optimize/architecting.md
Labels: Area: Documentation, Status: ▶️ Ready

#681 FX2024 Domain & Capabilities update / Quantify / Planning and Estimating
  docs/_docs/framework/capabilities/quantify/planning.md
Labels: Area: Documentation, Status: ▶️ Ready

#653 ADX for FinOpsHub
  src/templates/finops-hub/main.bicep
  src/templates/finops-hub/modules/adxTableSchema.kql
  src/templates/finops-hub/modules/dataExplorer.bicep
  src/templates/finops-hub/modules/hub.bicep
Labels: Status: ▶️ Ready, Solution: FinOps hubs

#684 FX2024 Domain & Capabilities update / Manage / FinOps tools and services
  docs/_docs/framework/capabilities/manage/tools-and-services.md
Labels: Area: Documentation, Needs: Review 👀
