Repository microsoft/finops-toolkit, pull requests merged in 2024-07, with the labels that each got.

#784 Add FinOps capability icons
  docs/svg/fx/allocation.png
  docs/svg/fx/allocation.svg
  docs/svg/fx/anomalies.png
  docs/svg/fx/anomalies.svg
  docs/svg/fx/architecting.png
  docs/svg/fx/architecting.svg
  docs/svg/fx/assessment.png
  docs/svg/fx/assessment.svg
  docs/svg/fx/benchmarking.png
  docs/svg/fx/benchmarking.svg
  docs/svg/fx/budgeting.png
  docs/svg/fx/budgeting.svg
  docs/svg/fx/chargeback.png
  docs/svg/fx/chargeback.svg
  docs/svg/fx/education.png
  docs/svg/fx/education.svg
  docs/svg/fx/forecasting.png
  docs/svg/fx/forecasting.svg
  docs/svg/fx/frameworks.png
  docs/svg/fx/frameworks.svg
  docs/svg/fx/ingestion.png
  docs/svg/fx/ingestion.svg
  docs/svg/fx/licensing.png
  docs/svg/fx/licensing.svg
  docs/svg/fx/onboarding.png
  docs/svg/fx/onboarding.svg
  docs/svg/fx/operations.png
  docs/svg/fx/operations.svg
  docs/svg/fx/planning.png
  docs/svg/fx/planning.svg
  docs/svg/fx/policy.png
  docs/svg/fx/policy.svg
  docs/svg/fx/rates.png
  docs/svg/fx/rates.svg
  docs/svg/fx/reporting.png
  docs/svg/fx/reporting.svg
  docs/svg/fx/sustainability.png
  docs/svg/fx/sustainability.svg
  docs/svg/fx/tools.png
  docs/svg/fx/tools.svg
  docs/svg/fx/uniteconomics.png
  docs/svg/fx/uniteconomics.svg
  docs/svg/fx/workloads.png
  docs/svg/fx/workloads.svg
Labels: Area: Documentation, Needs: Review 👀

#787 Update to FinOps hubs documented permissions prerequisites
  docs/_reporting/hubs/template.md
Labels: Area: Documentation, Needs: Review 👀

#798 Integrate AOE docs
  .github/workflows/aoe-cd-dev.yml
  docs/_config.yml
  docs/_optimize/governance-workbook/README.md
  docs/_optimize/governance-workbook/details.md
  docs/_optimize/optimization-engine/README.md
  docs/_optimize/optimization-engine/configuring-workspaces.md
  docs/_optimize/optimization-engine/customize.md
  docs/_optimize/optimization-engine/faq.md
  docs/_optimize/optimization-engine/reports.md
  docs/_optimize/optimization-engine/setup-options.md
  docs/_optimize/optimization-engine/suppressing-recommendations.md
  docs/_optimize/optimization-workbook/README.md
  docs/_optimize/optimization-workbook/cost-optimization-workbook.md
Labels: Area: Documentation, Status: ▶️ Ready

#765 Overview update
  src/workbooks/governance/workbook.json
Labels: Status: ▶️ Ready, Solution: Workbooks

#792 Remove deprecated FOCUS commands
  docs/_automation/powershell/README.md
  docs/_automation/powershell/focus/ConvertTo-FinOpsSchema.md
  docs/_automation/powershell/focus/Invoke-FinOpsSchemaTransform.md
  docs/_automation/powershell/focus/README.md
  docs/_resources/changelog.md
  src/powershell/Public/ConvertTo-FinOpsSchema.ps1
  src/powershell/Public/Invoke-FinOpsSchemaTransform.ps1
  src/powershell/Tests/Integration/FOCUS.Tests.ps1
  src/powershell/Tests/Unit/ConvertTo-FinOpsSchema.Tests.ps1
  src/powershell/Tests/Unit/Invoke-FinOpsSchemaTransform.Tests.ps1
Labels: Needs: Review 👀, Area: PowerShell

#794 Update Data ingestion report queries
  .gitignore
  docs/_reporting/power-bi/data-ingestion.md
  docs/_resources/changelog.md
  docs/_resources/troubleshooting.md
  src/power-bi/DataIngestion.Report/report.json
  src/power-bi/Shared.Dataset/definition/cultures/en-US.tmdl
  src/power-bi/Shared.Dataset/definition/expressions.tmdl
  src/power-bi/Shared.Dataset/definition/model.tmdl
  src/power-bi/Shared.Dataset/definition/relationships.tmdl
  src/power-bi/Shared.Dataset/definition/tables/CostDetails.tmdl
  src/power-bi/Shared.Dataset/definition/tables/HubData.tmdl
  src/power-bi/Shared.Dataset/definition/tables/HubExports.tmdl
  src/power-bi/Shared.Dataset/definition/tables/HubIngestion.tmdl
  src/power-bi/Shared.Dataset/definition/tables/HubScopes.tmdl
  src/power-bi/Shared.Dataset/definition/tables/HubSettings.tmdl
  src/power-bi/Shared.Dataset/definition/tables/LocalDateTable_0ac3758b-3ab8-42b7-bc85-9cfda5289f14.tmdl
  src/power-bi/Shared.Dataset/definition/tables/LocalDateTable_1cba35dd-c086-4d23-8329-b3c1c5cbdc70.tmdl
  src/power-bi/Shared.Dataset/definition/tables/LocalDateTable_41efb852-a77d-41a4-8d93-fa1942f528a3.tmdl
  src/power-bi/Shared.Dataset/definition/tables/LocalDateTable_767a87d5-01db-48e9-b034-577f5dc943a1.tmdl
  src/power-bi/Shared.Dataset/definition/tables/LocalDateTable_7e252193-4a78-4d83-a440-30c8768441b6.tmdl
  src/power-bi/Shared.Dataset/definition/tables/LocalDateTable_9c2ef32e-1f64-425a-80cf-53a4020c55fd.tmdl
  src/power-bi/Shared.Dataset/definition/tables/LocalDateTable_b4481e6d-7b57-4236-b430-b5260c37ff6f.tmdl
  src/power-bi/Shared.Dataset/definition/tables/LocalDateTable_c7280346-3e7b-4b97-8f9a-9eece9b5d3ed.tmdl
  src/power-bi/Shared.Dataset/definition/tables/LocalDateTable_f8c522a9-514b-435e-9c83-a31fe0c99a22.tmdl
  src/power-bi/Shared.Dataset/definition/tables/RecommendationsShared.tmdl
  src/power-bi/Shared.Dataset/definition/tables/RecommendationsSingle.tmdl
  src/power-bi/Shared.Dataset/diagramLayout.json
  src/templates/finops-hub/.buildignore
Labels: Needs: Review 👀, Solution: FinOps hubs

#795 Add FOCUS 1.0 schema file
  docs/_reporting/hubs/template.md
  src/templates/finops-hub/.buildignore
  src/templates/finops-hub/modules/scripts/Copy-FileToAzureBlob.ps1
  src/templates/finops-hub/modules/storage.bicep
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/CustomVisuals/HierarchySlicer1458836712039/package.json
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/CustomVisuals/HierarchySlicer1458836712039/resources/HierarchySlicer1458836712039.pbiviz.json
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/CustomVisuals/hierarchyChartByAkvelon6F792A8745784877BCD8F4ACA5AD4207/package.json
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/CustomVisuals/hierarchyChartByAkvelon6F792A8745784877BCD8F4ACA5AD4207/resources/hierarchyChartByAkvelon6F792A8745784877BCD8F4ACA5AD4207.pbiviz.json
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/RegisteredResources/ACMLearnMore3455599414129229.png
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/RegisteredResources/AzureCost_HeroAdjustment-Resize2x5775843843846507.png
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/RegisteredResources/Ibiza_Data_Visualization_Theme4744941034384995.json
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/RegisteredResources/LearnMore7090101546343053.png
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/RegisteredResources/feedback3410273840221807.png
  src/templates/finops-hub/reports/CommitmentDiscounts.Report/StaticResources/SharedResources/BaseThemes/CY19SU06.json
  src/templates/finops-hub/schema/README.md
  src/templates/finops-hub/schema/schema_ea_normalized.json
  src/templates/finops-hub/schema/schema_mca_normalized.json
  src/templates/finops-hub/schemas/README.md
  src/templates/finops-hub/schemas/focuscost_1.0-preview(v1).json
Labels: Needs: Review 👀, Tool: FinOps hubs

#764 Handle unsupported EventGrid regions
  docs/_docs/framework/capabilities/optimize/rates.md
  docs/_reporting/hubs/configure-scopes.md
  docs/_reporting/hubs/template.md
  docs/deploy/governance-workbook-0.2.1-rc.2.json
  docs/deploy/governance-workbook-0.2.1-rc.3.json
  docs/deploy/governance-workbook-0.2.1.json
  docs/deploy/governance-workbook-0.3.json
  docs/deploy/governance-workbook-latest.json
  docs/deploy/optimization-workbook-0.2.1-rc.2.json
  docs/deploy/optimization-workbook-0.2.1-rc.3.json
  docs/deploy/optimization-workbook-0.2.1.json
  docs/deploy/optimization-workbook-0.3.json
  docs/deploy/optimization-workbook-latest.json
  src/open-data/ResourceTypes.json
  src/powershell/Private/Get-OpenDataResourceType.ps1
  src/powershell/Public/Get-FinOpsCostExport.ps1
  src/templates/finops-hub/main.bicep
  src/templates/finops-hub/modules/dataFactory.bicep
  src/templates/finops-hub/modules/hub.bicep
  src/templates/finops-hub/modules/storage.bicep
  src/workbooks/governance/workbook.json
  src/workbooks/optimization/CostOptimization.workbook
  src/workbooks/optimization/Databases/Databases.workbook
  src/workbooks/optimization/Networking/Networking.workbook
  src/workbooks/optimization/Reservations Preview/ReservationsPreview.workbook
  src/workbooks/optimization/Reservations/Reservations.workbook
  src/workbooks/optimization/SavingsPlan/SavingsPlan.workbook
  src/workbooks/optimization/Top10Services/Top10Services.workbook
  src/workbooks/optimization/workbook.json
Labels: Needs: Review 👀, Tool: FinOps hubs

#800 Update issue and PR policies
  .github/policies/issues-00-conventions.yml
  .github/policies/issues-01-new.yml
  .github/policies/pulls-00-checklist.yml
  .github/policies/pulls-00-file-paths.yml
  .github/policies/pulls-04-approve.yml
Labels: Needs: Review 👀, Area: DevOps

#791 Update template doc
  docs/_reporting/hubs/template.md
  src/templates/finops-hub/modules/hub.bicep
Labels: Needs: Review 👀, Tool: FinOps hubs

#796 Update FOCUS docs to 1.0
  docs/_docs/focus/README.md
  docs/_docs/focus/convert.md
  docs/_docs/focus/mapping.md
  docs/_resources/changelog.md
  docs/_resources/data-dictionary.md
  docs/_resources/terms.md
Labels: Skill: Documentation, Needs: Review 👀, Tool: FinOps guide

#767 Update details.md for Governance Workbook
  docs/_optimize/governance-workbook/details.md
Labels: Skill: Documentation, Status: ▶️ Ready, Skill: Workbooks, Tool: Governance workbook

#785 Require PowerShell 7 + handle throttling errors
  .build/BuildHelper/Build-PsModule.ps1
  docs/_automation/powershell/README.md
  docs/_automation/powershell/cost/Start-FinOpsCostExport.md
  docs/_resources/changelog.md
  src/powershell/Private/Invoke-Rest.ps1
  src/powershell/Public/Start-FinOpsCostExport.ps1
  src/powershell/Tests/Integration/CostExports.Tests.ps1
  src/powershell/Tests/Unit/Start-FinOpsCostExport.Tests.ps1
Labels: Needs: Review 👀, Tool: PowerShell

#793 Default to FOCUS 1.0 in New-FinOpsCostExport
  docs/_automation/powershell/cost/New-FinOpsCostExport.md
  docs/_resources/changelog.md
  src/powershell/Public/New-FinOpsCostExport.ps1
Labels: Needs: Review 👀, Tool: PowerShell

#804 Updated changelog and fixed workbook links
  docs/_docs/framework/capabilities/manage/tools-and-services.md
  docs/_docs/framework/capabilities/optimize/sustainability.md
  docs/_docs/framework/capabilities/optimize/workloads.md
  docs/_docs/framework/capabilities/quantify/planning.md
  docs/_resources/changelog.md
  docs/_resources/deploy.md
Labels: Needs: Review 👀

#807 Fix Data ingestion report region filter
  src/power-bi/CostSummary.Report/report.json
  src/power-bi/DataIngestion.Report/report.json
Labels: Micro PR 🔬, Needs: Review 👀

#808 Update PR policy file paths
  .github/policies/pulls-02-reviewers.yml
Labels: Micro PR 🔬, Skill: DevOps, Needs: Review 👀

#811 Fix breaking change PR policy
  .github/policies/pulls-01-checklist.yml
Labels: Skill: DevOps, Needs: Review 👀

#813 Expand workload optimization capability doc
  docs-wiki/Support-escalations.md
  docs/_docs/framework/capabilities/optimize/workloads.md
Labels: Micro PR 🔬, Needs: Review 👀

#815 Integrate Arthur's TSG into existing docs
  docs/_config.yml
  docs/_includes/components/site_nav.html
  docs/_resources/README.md
  docs/_resources/changelog.md
  docs/_resources/data-dictionary.md
  docs/_resources/deploy.md
  docs/_resources/errors.md
  docs/_resources/support.md
  docs/_resources/terms.md
  docs/_resources/troubleshooting.md
Labels: Skill: Documentation, Needs: Review 👀

#821 Update policies to account for the deployment label
  .github/policies/issues-00-conventions.yml
  .github/policies/pulls-02-reviewers.yml
Labels: Skill: DevOps, Needs: Review 👀

#824 Fixing missing retention settings when upgrading hubs from 0.3 ot 0.4
  .github/workflows/aoe-cd-dev.yml
  .github/workflows/aoe-cd-prod.yml
  .github/workflows/aoe-cd-test.yml
  src/templates/finops-hub/modules/scripts/Copy-FileToAzureBlob.ps1
Labels: Needs: Review 👀, Tool: FinOps hubs

#810 Add main.bicep file for waste reduction logic app
  src/logic-apps/waste-reduction/README.md
  src/logic-apps/waste-reduction/createUIDefinition.json
  src/logic-apps/waste-reduction/main.bicep
  src/logic-apps/waste-reduction/metadata.json
Labels: Breaking change 🚨, Needs: Attention 👋

#830 Update roadmap after 0.4 release
  docs-wiki/Roadmap.md
Labels: Skill: Documentation, Micro PR 🔬, Needs: Review 👀

#833 Updated changelog for Azure Governance workbook v0.4
  docs/_resources/changelog.md
Labels: Skill: Documentation, Needs: Review 👀

#832 Update wiki-sync action
  .github/workflows/wiki-sync.yml
Labels: Micro PR 🔬, Skill: DevOps, Needs: Review 👀

#844 Waste Reduction Logic App README.md
  docs/_automation/waste-reduction-logic-app/README.md
  docs/_automation/waste-reduction-logic-app/images/Authorize-&-Save.png
  docs/_automation/waste-reduction-logic-app/images/Azure-role-assignment.png
  docs/_automation/waste-reduction-logic-app/images/Edit-API-connection.png
  docs/_automation/waste-reduction-logic-app/images/Logic-app-designer.png
  docs/_automation/waste-reduction-logic-app/images/System-assigned-identity.png
Labels: Skill: Documentation, Needs: Review 👀

#843 Correctly schedule exports
  src/templates/finops-hub/modules/dataFactory.bicep
Labels: Type: Bug 🐛, Micro PR 🔬, Skill: Deployment, Tool: FinOps hubs

#851 Add PR policy for changelog and docs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/policies/pulls-01-checklist.yml
Labels: Skill: DevOps, Needs: Review 👀

#847 Remove outdated warning + improve dataset version detection
  src/power-bi/RateOptimization.Report/report.json
  src/power-bi/Shared.Dataset/definition/expressions.tmdl
  src/power-bi/Shared.Dataset/definition/model.tmdl
  src/power-bi/Shared.Dataset/definition/tables/RecommendationsSingle.tmdl
Labels: Tool: Power BI, Needs: Review 👀

#848 Add MS Learn modules to the overview
  docs/README.md
  docs/_resources/troubleshooting.md
Labels: Skill: Documentation, Micro PR 🔬, Needs: Review 👀

#855 Hubs managed exports deployment instructions / Fix pipeline name
  docs/_reporting/hubs/configure-scopes.md
Labels: Skill: Documentation, Micro PR 🔬, Needs: Review 👀, Tool: FinOps hubs

#850 Get-FinOpsCostExport -DatasetVersion and new dataset types
  docs/_resources/changelog.md
  src/powershell/Public/Get-FinOpsCostExport.ps1
  src/powershell/Public/New-FinOpsCostExport.ps1
  src/powershell/Public/Remove-FinOpsCostExport.ps1
  src/powershell/en-US/FinOpsToolkit.strings.psd1
Labels: Needs: Review 👀, Tool: PowerShell
