Repository microsoft/finops-toolkit, pull requests merged in 2024-03, with the labels that each got.

#633 Updating workbook feature branch
  src/workbooks/optimization/AHB/AHB.workbook
  src/workbooks/optimization/Compute/Compute.workbook
  src/workbooks/optimization/Networking/Networking.workbook
  src/workbooks/optimization/README.md
  src/workbooks/optimization/Reservations/Reservations.workbook
  src/workbooks/optimization/SavingsPlan/SavingsPlan.workbook
  src/workbooks/optimization/Storage/Storage.workbook
  src/workbooks/optimization/Top10Services/Top10Services.workbook
  src/workbooks/optimization/workbook.json
Labels: Needs: Review 👀, Solution: Workbooks

#631 Workbook - Feb release
  docs/_resources/changelog.md
  src/workbooks/optimization/AHB/AHB.workbook
  src/workbooks/optimization/Compute/Compute.workbook
  src/workbooks/optimization/Networking/Networking.workbook
  src/workbooks/optimization/Reservations/Reservations.workbook
  src/workbooks/optimization/SavingsPlan/SavingsPlan.workbook
  src/workbooks/optimization/Storage/Storage.workbook
  src/workbooks/optimization/Top10Services/Top10Services.workbook
  src/workbooks/optimization/workbook.json
Labels: Solution: Workbooks

#651 Governance workbook updates
  docs-wiki/Release-process.md
  docs-wiki/_Sidebar.md
  docs/_resources/changelog.md
  src/workbooks/governance/workbook.json
Labels: Needs: Review 👀, Solution: Workbooks

#655 Update tests for v0.2
  docs-wiki/Release-process.md
  src/powershell/Tests/Integration/Toolkit.Tests.ps1
Labels: Needs: Review 👀

#654 Fix FOCUS dataset version (changed by CM exports)
  docs/_automation/powershell/cost/New-FinOpsCostExport.md
  docs/_reporting/data/README.md
  docs/_reporting/hubs/README.md
  docs/_resources/changelog.md
  src/power-bi/Shared.Dataset/model.bim
  src/power-bi/queries/ftk_CostDetails.pq
  src/power-bi/queries/ftk_Hub.pq
  src/powershell/Public/New-FinOpsCostExport.ps1
  src/templates/finops-hub/modules/dataFactory.bicep
Labels: Needs: Review 👀

#658 Fix start/end time for one-time exports
  docs/_automation/powershell/cost/New-FinOpsCostExport.md
  docs/_resources/changelog.md
  src/powershell/Public/New-FinOpsCostExport.ps1
  src/powershell/Tests/Integration/CostExports.Tests.ps1
Labels: Needs: Review 👀

#659 Test cleanup
  docs/_resources/changelog.md
  src/power-bi/DataIngestion.Report/.platform
  src/powershell/Private/Save-FinOpsHubTemplate.ps1
  src/powershell/Tests/Unit/Get-FinOpsToolkitVersion.Tests.ps1
  src/powershell/Tests/Unit/LocalizedData.Tests.ps1
  src/powershell/Tests/Unit/New-Directory.Tests.ps1
  src/powershell/Tests/Unit/Save-FinOpsHubTemplate.Tests.ps1
  src/powershell/Tests/Unit/Toolkit.Tests.ps1
  src/scripts/Test-PowerShell.ps1
Labels: Needs: Review 👀

#637 Add contributors guideline
  .github/ISSUE_TEMPLATE/propose-tool.md
  docs/_resources/contributors.md
Labels: Area: Documentation, Needs: Review 👀

#661 Explicitly call out that the connector report works for MCA
  docs/_reporting/power-bi/README.md
  docs/_resources/changelog.md
Labels: Area: Documentation, Needs: Review 👀
