Repository microsoft/finops-toolkit, pull requests merged in 2025-06, with the labels that each got.

#1651 Handle FOCUS 1.2 gracefully
  docs-mslearn/toolkit/changelog.md
  src/power-bi/storage/Shared.Dataset/definition/tables/Costs.tmdl
  src/powershell/Public/New-FinOpsCostExport.ps1
  src/templates/finops-hub/docs/README.md
  src/templates/finops-hub/modules/scripts/HubSetup.kql
  src/templates/finops-hub/modules/scripts/IngestionSetup_RawTables.kql
  src/templates/finops-hub/modules/scripts/IngestionSetup_v1_0.kql
  src/templates/finops-hub/modules/scripts/README.md
  src/templates/finops-hub/modules/storage.bicep
  src/templates/finops-hub/schemas/focuscost_1.2-preview.json
  src/templates/finops-hub/schemas/focuscost_1.2.json
Labels: Needs: Review 👀

#1644 Document 0.9/10 upgrade and capability
  docs-mslearn/toolkit/changelog.md
Labels: Needs: Review 👀

#1656 Hubs 0.11 deployment fix
  src/templates/finops-hub/modules/scripts/IngestionSetup_RawTables.kql
  src/templates/finops-hub/modules/scripts/IngestionSetup_v1_0.kql
Labels: Needs: Review 👀, Tool: FinOps hubs, Skill: KQL

#1659 Hubs upgrade fixes
  docs/deploy/finops-hub-0.11.json
  docs/deploy/finops-hub-latest.json
  src/scripts/Package-Toolkit.ps1
  src/templates/finops-hub/modules/hub-types.bicep
  src/templates/finops-hub/modules/scripts/IngestionSetup_RawTables.kql
Labels: Micro PR 🔬, Needs: Review 👀

#1661 Update README.md Template path
  src/wacoa/README.md
Labels: Skill: DevOps, Needs: Review 👀

#1664 Fix Copilot setup doc
  docs-mslearn/index.yml
  docs-mslearn/toolkit/hubs/configure-ai.md
  docs-mslearn/toolkit/hubs/deploy.md
  docs-mslearn/toolkit/power-bi/invoicing.md
  docs-mslearn/toolkit/power-bi/setup.md
Labels: Micro PR 🔬, Needs: Review 👀

#1680 Power BI updates
  docs-mslearn/toolkit/power-bi/media/rate-optimization/hybrid-benefit.png
  docs-mslearn/toolkit/power-bi/media/rate-optimization/reservation-recommendations.png
  src/power-bi/kql/CostSummary.Report/report.json
  src/power-bi/kql/DataIngestion.Report/definition.pbir
  src/power-bi/kql/DataIngestion.Report/report.json
  src/power-bi/kql/DataIngestion.kql.pbip
  src/power-bi/kql/Governance.Report/report.json
  src/power-bi/kql/RateOptimization.Report/definition.pbir
  src/power-bi/kql/RateOptimization.Report/report.json
  src/power-bi/kql/RateOptimization.kql.pbip
  src/power-bi/kql/Shared.Dataset/definition/model.tmdl
  src/power-bi/kql/WorkloadOptimization.Report/definition.pbir
  src/power-bi/kql/WorkloadOptimization.Report/report.json
  src/power-bi/kql/WorkloadOptimization.kql.pbip
  src/power-bi/storage/CostSummary.Report/report.json
  src/power-bi/storage/DataIngestion.Report/definition.pbir
  src/power-bi/storage/DataIngestion.Report/report.json
  src/power-bi/storage/DataIngestion.storage.pbip
  src/power-bi/storage/Governance.Report/report.json
  src/power-bi/storage/Invoicing.Report/report.json
  src/power-bi/storage/RateOptimization.Report/definition.pbir
  src/power-bi/storage/RateOptimization.Report/report.json
  src/power-bi/storage/RateOptimization.storage.pbip
  src/power-bi/storage/Shared.Dataset/definition/model.tmdl
  src/power-bi/storage/Shared.Dataset/diagramLayout.json
  src/power-bi/storage/WorkloadOptimization.Report/definition.pbir
  src/power-bi/storage/WorkloadOptimization.Report/report.json
  src/power-bi/storage/WorkloadOptimization.storage.pbip
  src/scripts/Build-PowerBI.ps1
Labels: Needs: Review 👀

#1671 Prep for v0.12
  docs-mslearn/toolkit/changelog.md
  docs/_includes/ftkver.txt
  package-lock.json
  package.json
  src/optimization-engine/ftkver.txt
  src/powershell/Private/Get-VersionNumber.ps1
  src/powershell/Tests/Integration/Toolkit.Tests.ps1
  src/templates/finops-alerts/modules/ftkver.txt
  src/templates/finops-hub/modules/ftkver.txt
  src/templates/finops-workbooks/ftkver.txt
  src/workbooks/.scaffold/ftkver.txt
Labels: Micro PR 🔬, Needs: Review 👀

#1684 policyDefinition Azure Resource Graph query optimization
  src/power-bi/kql/Governance.Report/report.json
  src/power-bi/kql/Shared.Dataset/definition/expressions.tmdl
  src/power-bi/storage/Governance.Report/report.json
  src/power-bi/storage/Shared.Dataset/definition/expressions.tmdl
  src/power-bi/storage/Shared.Dataset/definition/tables/Costs.tmdl
Labels: Tool: Power BI, Needs: Review 👀

#1706 Updated the Workload Optimization report and adjusted the table structure to handle cases with empty results
  src/power-bi/kql/Governance.Report/report.json
  src/power-bi/kql/Shared.Dataset/definition/model.tmdl
  src/power-bi/kql/Shared.Dataset/definition/tables/Resources.tmdl
  src/power-bi/storage/Governance.Report/report.json
  src/power-bi/storage/Shared.Dataset/definition/model.tmdl
  src/power-bi/storage/Shared.Dataset/definition/tables/Resources.tmdl
  src/power-bi/storage/WorkloadOptimization.Report/report.json
Labels: Micro PR 🔬, Tool: Power BI, Needs: Review 👀

#1709 Add exec summary page to Cost Summary report
  docs-mslearn/toolkit/changelog.md
  docs-mslearn/toolkit/power-bi/cost-summary.md
  docs-mslearn/toolkit/power-bi/media/cost-summary/running-total.png
  docs-mslearn/toolkit/power-bi/media/cost-summary/summary.png
  src/power-bi/kql/CostSummary.Report/report.json
  src/power-bi/kql/Shared.Dataset/definition/cultures/en-US.tmdl
  src/power-bi/kql/Shared.Dataset/definition/model.tmdl
  src/power-bi/storage/CostSummary.Report/report.json
  src/power-bi/storage/Shared.Dataset/definition/cultures/en-US.tmdl
  src/power-bi/storage/Shared.Dataset/definition/model.tmdl
  src/power-bi/storage/Shared.Dataset/definition/tables/Costs.tmdl
Labels: Tool: Power BI, Needs: Review 👀

#1670 [Hub apps] Extract apps for hub core and CM exports
  src/templates/finops-hub/modules/cm-exports.bicep
  src/templates/finops-hub/modules/core.bicep
  src/templates/finops-hub/modules/hub-app.bicep
  src/templates/finops-hub/modules/hub-deploymentScript.bicep
  src/templates/finops-hub/modules/hub-identity.bicep
  src/templates/finops-hub/modules/hub-storage.bicep
  src/templates/finops-hub/modules/hub.bicep
  src/templates/finops-hub/modules/remoteHub.bicep
  src/templates/finops-hub/modules/storage.bicep
Labels: Skill: Deployment, Needs: Review 👀, Tool: FinOps hubs

#1715 Expanded Recommendations dataset column
  docs-mslearn/toolkit/changelog.md
  docs-mslearn/toolkit/hubs/data-model.md
  docs-mslearn/toolkit/hubs/upgrade.md
  src/templates/finops-hub/modules/scripts/IngestionSetup_RawTables.kql
  src/templates/finops-hub/modules/scripts/IngestionSetup_v1_2.kql
Labels: Needs: Review 👀

#1637 Start Data Explorer when stopped
  docs-mslearn/toolkit/changelog.md
  docs-mslearn/toolkit/hubs/data-processing.md
  src/templates/finops-hub/modules/dataFactory.bicep
Labels: Needs: Review 👀

#1713 Change default FOCUS version to 1.2-preview
  docs-mslearn/toolkit/changelog.md
  docs-mslearn/toolkit/powershell/cost/get-finopscostexport.md
  docs-mslearn/toolkit/powershell/cost/new-finopscostexport.md
  docs-mslearn/toolkit/powershell/cost/remove-finopscostexport.md
  docs-mslearn/toolkit/powershell/cost/start-finopscostexport.md
  src/powershell/Public/Get-FinOpsCostExport.ps1
  src/powershell/Public/New-FinOpsCostExport.ps1
  src/powershell/Public/Remove-FinOpsCostExport.ps1
  src/powershell/Public/Start-FinOpsCostExport.ps1
  src/powershell/Tests/Integration/CostExports.Tests.ps1
  src/powershell/Tests/Unit/New-FinOpsCostExport.Tests.ps1
Labels: Needs: Review 👀

#1655 Addition of MoM Large Swings report
  src/power-bi/storage/AnomalyManagement.Report/report.json
  src/power-bi/storage/Shared.Dataset/definition/cultures/en-US.tmdl
  src/power-bi/storage/Shared.Dataset/definition/model.tmdl
  src/power-bi/storage/Shared.Dataset/definition/relationships.tmdl
  src/power-bi/storage/Shared.Dataset/definition/tables/Costs.tmdl
  src/power-bi/storage/Shared.Dataset/definition/tables/DateTable.tmdl
  src/power-bi/storage/Shared.Dataset/definition/tables/MaxDeltaCost.tmdl
  src/power-bi/storage/Shared.Dataset/definition/tables/MinDeltaCost.tmdl
  src/power-bi/storage/Shared.Dataset/diagramLayout.json
Labels: Tool: Power BI, Needs: Attention 👋
